--- # when playbook example
- hosts: all
  # user: root
  # sudo: yes
  connection: ssh
  gather_facts: yes
  vars:
    playbook_type: conditional example

  tasks:
    - name: Install apache to the distribution type(Centos7)
      command: yum install httpd -y
      when: ansible_os_family == "RedHat"
    - name: Install apache to the distribution type(RedHat)
      command: apt-get install apache2 -y
      when: ansible_os_family == "Debian"